### ISSUE TITLE
【BUG】无法从“markupsafe”导入名称“soft_unicode”

### ISSUE THREAD

**Issue by ghost** [hustcc/PyG2Plot#32]
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
> `from pyg2plot import Plot`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\pyg2plot\__init__.py", line 9, in <module>
    from pyg2plot.plot import Plot # noqa
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\pyg2plot\plot.py", line 9, in <module>
    from jinja2 import Environment
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\markupsafe\__init__.py)

> `import pyg2plot`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\pyg2plot\__init__.py", line 9, in <module>
    from pyg2plot.plot import Plot # noqa
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\pyg2plot\plot.py", line 9, in <module>
    from jinja2 import Environment
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\梦云之家\AppData\Roaming\Python\Python310\site-packages\markupsafe\__init__.py)

**Comment by caicaiw** [comment]
hi，have you solved it?

**Comment by caicaiw** [comment]
I seem to have figured it out. I suggest you change the version of Jinja2, for example, 3.0.3.

**Comment by a497823463** [comment]
from markupsafe import soft_str as soft_unicode

**Comment by a497823463** [comment]
2年没更新了，......
